### PR TITLE
Make it possible to extract data from data.tar.zst from deb packages

### PR DESCRIPTION
**Pull request by vzhestkov**
`Ubuntu 22.04` is using `data.tar.zst` instead of `data.tar.xz`.

### CODE REVIEW

**Review by aplanas — CHANGES_REQUESTED** [review]
Can you move the condition into Python?

**Comment by vzhestkov** [comment]
@aplanas yes, I can, but I have another suggestion. Maybe we can use `dpkg-deb -x DEB_PACKAGE DEST_DIR` instead of combination of `ar` and `tar` ? The only point I'm not sure about is `--keep-directory-symlink` tar option. I've tried to extract the package data in both ways on debian based system and I didn't find any difference. Do you remember why `--keep-directory-symlink` was used?

**Comment by aplanas** [comment]
>  Maybe we can use `dpkg-deb -x DEB_PACKAGE DEST_DIR` instead of combination of `ar` and `tar` ? 

I would prefer not, as will add new dependencies, unless it is not accurately replicated with ar / tar.

>The only point I'm not sure about is `--keep-directory-symlink` tar option. I've tried to extract the package data in both ways on debian based system and I didn't find any difference. Do you remember why `--keep-directory-symlink` was used?

I think that this was required for some packages, not all of them, that use links.  IIRC was required to avoid duplication.

**Comment by vzhestkov** [comment]
Basically `dpkg-deb` is not an extra dependency. On debian based systems `ar` could be missing, but `dpkg-deb` is always present and it extracts the data from the package with the single command. The only fear I have is about this particular parameter.

**Comment by aplanas** [comment]
> Basically `dpkg-deb` is not an extra dependency.

Ah right. I totally forgot that it will be executed in an Ubuntu machine already.

> The only fear I have is about this particular parameter.

I confess that I do not have any idea how dpkg-deb will behave. Do a PR, I will merge. You can update the package and see if does the right thing. If not we can revert it.

**Comment by vzhestkov** [comment]
I think it's better to check in OBS with no merging it right now. I'll put this change as a patch for `vevjail` package. Will update the PR on the results of testing :+1:

**Comment by vzhestkov** [comment]
@aplanas I understand the reason of using `--keep-directory-symlink`. Without it it will overwrite the destination symlinks to directories with the directories.
I put the condition to the python, but to be fair I like the previous solutuion less complicated.

**Comment by aplanas** [comment]
> I put the condition to the python, but to be fair I like the previous solutuion less complicated.

Right. It is a mess, but I think that there is some room to improve it:

* Remove the first commit
* did you try autodetect?

```
f"cd {directory}; ar x {package}; "
  "tar --keep-directory-symlink -xavf data.tar.*; "
  "rm control.tar.xz data.tar.* debian-binary",
```

Edit: I am not sure if autodetect will work on Ubuntu

**Comment by vzhestkov** [comment]
Hmm, I haven't. Let me check.

**Comment by aplanas** [comment]
> Hmm, I haven't. Let me check.

Technically should work even without "-a", and now that I read it "-v" is useless:

```
f"cd {directory}; ar x {package}; "
  "tar --keep-directory-symlink -xf data.tar.*; "
  "rm control.tar.xz data.tar.* debian-binary",
```

**Comment by vzhestkov** [comment]
Thanks @aplanas just checked in OBS and it works. Updated the PR. Thanks a lot for the suggestion :+1:

**Review by aplanas — APPROVED** [review]

**Pull request merged**
